# Generated by Django 5.2 on 2025-04-24 05:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('aborted', 'Aborted'), ('time_out', 'Time Out'), ('within_time', 'Within Time')], max_length=20)),
                ('points_scored', models.PositiveIntegerField(blank=True, null=True)),
                ('max_points', models.PositiveIntegerField(blank=True, null=True)),
                ('hint_penalty_points', models.PositiveIntegerField(default=0)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('tools_earned', models.JSONField(default=list)),
                ('badges', models.JSONField(default=list)),
                ('super_powers', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Game Progress',
                'unique_together': {('user', 'level', 'attempt_number')},
            },
        ),
    ]
