# Generated by Django 5.2.14 on 2026-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
