# Generated by Django 5.2.14 on 2026-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activesession_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
