# Generated by Django 5.2 on 2025-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usergameprogress_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameprogress',
            name='user_data',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_data',
            field=models.JSONField(default=list),
        ),
    ]
