# Generated by Django 5.2.9 on 2026-05-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_webglsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webglsession',
            name='task_number',
        ),
    ]
