# Generated by Django 5.2.9 on 2026-04-06 13:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_id',
            field=models.CharField(blank=True, default=accounts.models.generate_group_id, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
