# Generated by Django 5.2.5 on 2025-12-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activesession_logout_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
