# Generated by Django 5.2.9 on 2026-04-06 13:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_country_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_id',
            field=models.CharField(blank=True, default=accounts.models.generate_group_id, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
