# Generated by Django 5.2.9 on 2026-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_group_remove_customuser_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
