# Generated by Django 5.2.5 on 2025-12-11 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
