# Generated by Django 5.2.5 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
